apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: labkube-2
  name: labkube-2
spec:
  replicas: 2
  selector:
    matchLabels:
      run: labkube
      instances: type2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: labkube
        instances: type2
    spec:
      containers:
      - image: dbenque/labkube:v1
        env:
        - name: MY_DEPLOYMENT
          value: "My deployment is labkube-2"
        name: labkube
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 30