apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: labkube-1
  name: labkube-cm
spec:
  replicas: 2
  selector:
    matchLabels:
      run: labkube
      instances: type-cm
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: labkube
        instances: type-cm
    spec:
      containers:
      - image: dbenque/labkube:v1
        env:
        - name: KEY_FROM_CM
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: file1.txt
        - name: MY_DEPLOYMENT
          value: "My deployment is labkube-cm"
        name: labkube
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 30